### ISSUE TITLE
Need an appropriate loader to handle this file type

### ISSUE THREAD

**Issue by pcg92** [KirillGudkov/mvp-di#1]
Im trying to use this lib but im getting this error

Inject.ts:1 Uncaught Error: Module parse failed: Unexpected token (6:22)
You may need an appropriate loader to handle this file type.
| import {MvpView} from "./MvpView";

**Comment by kirgudkov** [comment]
Hi, hope You don't use vanilla JS? The lib was designed to use with TypeScript and obviously problem with `tsconfig.json` or `.babelrc`.
There is my `tsconfig.json`:
```
{
  "compilerOptions": {
    "allowJs": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "isolatedModules": true,
    "jsx": "react-native",
    "lib": ["es6"],
    "moduleResolution": "node",
    "noEmit": true,
    "strict": true,
    "target": "esnext"
  },
  "exclude": ["node_modules"]
}
```

And `.babelrc`:
```
{
  "presets": ["module:metro-react-native-babel-preset"],
  "plugins": [
    ["@babel/plugin-proposal-decorators", { "legacy": true }]]
}
```

Try it, hope this help

And that's my sandbox - https://github.com/KirillGudkov/react-native-sandbox
You could find some examples over there. 
https://github.com/KirillGudkov/react-native-sandbox/blob/master/src/Screen/Home/Home.tsx
https://github.com/KirillGudkov/react-native-sandbox/blob/master/src/Presenter/HomePresenter.ts
for example
